# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseApp',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=45)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=45)),
                ('root_password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'autoscaling_database_app',
            },
        ),
        migrations.CreateModel(
            name='DatabaseImage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_db', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('image_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'autoscaling_database_image',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=30)),
                ('upper_threshold', models.FloatField()),
                ('lower_threshold', models.FloatField()),
                ('instances_out', models.IntegerField()),
                ('instances_in', models.IntegerField()),
                ('scale_up_wait', models.IntegerField()),
                ('scale_down_wait', models.IntegerField()),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'autoscaling_policies',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'autoscaling_setting',
            },
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('github_url', models.CharField(max_length=255)),
                ('min_instances', models.IntegerField()),
                ('max_instances', models.IntegerField()),
                ('autoscaling', models.CharField(default='off', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'autoscaling_web_app',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='web_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.WebApp'),
        ),
        migrations.AddField(
            model_name='databaseapp',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.DatabaseImage'),
        ),
        migrations.AddField(
            model_name='databaseapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
