# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=45)),
                ('port', models.IntegerField()),
                ('root_password', models.CharField(max_length=60)),
                ('mysql_version', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'autoscaling_database_app',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=30)),
                ('upper_threshold', models.FloatField()),
                ('lower_threshold', models.FloatField()),
                ('instances_out', models.IntegerField()),
                ('instances_in', models.IntegerField()),
                ('scale_up_wait', models.IntegerField()),
                ('scale_down_wait', models.IntegerField()),
                ('disabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('apache_version', models.CharField(max_length=10)),
                ('min_instances', models.IntegerField()),
                ('max_instances', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'autoscaling_web_app',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='web_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.WebApp'),
        ),
    ]
