# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='autoscaling',
            field=models.CharField(default='off', max_length=255),
        ),
    ]
